name: build

on:
  push:
  pull_request:
  schedule:
      - cron: '0 0 * * *'

jobs:
    tests:
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: true
            matrix:
                php: [7.0, 7.1, 7.2, 7.3, 7.4, 8.0]
                laravel: [5.5.*, 5.6.*, 5.7.*, 5.8.*, 6.*, 7.*, 8.*]
                dependency-version: [prefer-lowest, prefer-stable]
                os: [ubuntu-latest, windows-latest]
                exclude:
                    - laravel: 5.5.*
                      php: 8.0
                    - laravel: 5.6.*
                      php: 7.0
                    - laravel: 5.6.*
                      php: 8.0
                    - laravel: 5.7.*
                      php: 7.0
                    - laravel: 5.7.*
                      php: 8.0
                    - laravel: 5.8.*
                      php: 7.0
                    - laravel: 5.8.*
                      php: 8.0
                    - laravel: 6.*
                      php: 7.0
                    - laravel: 6.*
                      php: 7.1
                    - laravel: 6.*
                      php: 8.0
                      dependency-version: prefer-lowest
                    - laravel: 7.*
                      php: 7.0
                    - laravel: 7.*
                      php: 7.1
                    - laravel: 8.*
                      php: 7.0
                    - laravel: 8.*
                      php: 7.1
                    - laravel: 8.*
                      php: 7.2
                    - os: windows-latest
                      php: 8.0

        name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip
                  tools: composer:v2
                  coverage: none

            - name: Install dependencies
              run: |
                  composer require "illuminate/contracts=${{ matrix.laravel }}" --no-interaction --no-update
                  composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

            - name: Execute tests
              run: vendor/bin/phpunit --verbose

    coverage:
        runs-on: ubuntu-latest

        name: Coverage

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.4
                  extensions: dom, curl, libxml, mbstring, zip
                  tools: composer:v2
                  coverage: xdebug

            - name: Install dependencies
              run: composer update --prefer-stable --prefer-dist --no-interaction

            - name: Execute tests
              run: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

            - name: Upload coverage
              run: |
                wget https://scrutinizer-ci.com/ocular.phar
                php ocular.phar code-coverage:upload --format=php-clover coverage.clover

    style:
        runs-on: ubuntu-latest

        name: Coding style

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.0
                  tools: phpcs
                  coverage: none

            - name: Execute check
              run: phpcs --standard=psr12 src/ tests/